/*******************************************************
*      Copyright (C) 1998,1999  Greg Landrum
*
*  This file is part of yaehmop.
*
*   This is free software.
* 
*  Permission is granted to modify, or otherwise fold, spindle, and mutilate this
*    code provided all copyright notices are left intact.
*
*  This code may be distributed to your heart's content, in whatever form,
*    provided no fee is charged for the distribution, all copyright notices are
*    left intact, and the source is distributed (without fee) along with any
*    binaries to anyone who requests it.
*
*  There are, of course, no warranties at all on this program.
*
********************************************************************/

/***

 created by gL: July 1998

 ***/

char *VRML_header[] = {
"#VRML V2.0 utf8",
"# Automagically generated by viewkel",
"PROTO diffball [ field SFFloat MyRadius 0.2",
"		 field SFColor MyColor .6 .6 .6]",
"{Shape {",
"    geometry Sphere { radius IS MyRadius }",
"    appearance Appearance {",
"	material Material {diffuseColor IS MyColor}",
"    }",
"}}",
"PROTO diffcyl [  field SFFloat MyRadius .10",
"		 field SFFloat MyHeight 1.0",
"		 field SFColor MyColor .6 .6 .6]",
"{",
"Shape {",
"    geometry Cylinder { radius IS MyRadius height IS MyHeight",
"                          bottom FALSE top FALSE}",
"    appearance Appearance {",
"	material Material {diffuseColor IS MyColor}",
"    }}}",
"NavigationInfo { type [\"EXAMINE\", \"ANY\"]}",
"WorldInfo{ title \"From viewkel!!!\" }",
"DEF FarView Viewpoint {",
"position 0 0 20",
"description \"Farther\"",
"orientation 0 0 1 0",
"}",
"DEF YView Viewpoint {",
"position 0 20 0",
"description \"Y-axis\"",
"orientation 1 0 0 -1.57",
"}",
"DEF XView Viewpoint {",
"position 20 0 0",
"description \"X-axis\"",
"orientation 0 1 0 1.57",
"}",
"DEF CloseView Viewpoint {",
"position 0 0 10",
"description \"Close!\"",
"orientation 0 0 1 0",
"}",
"PROTO arrow [field MFString MyLabel \"y\"",
"             field SFColor ArrColor 0.6 0.6 0.6]",
"{",
"Group { children[",
"Transform {translation 0 1 0 children[",
"Shape { geometry Cylinder {radius 0.1 height 2",
"                           top FALSE bottom FALSE}",
"    appearance Appearance {",
"	material Material {diffuseColor IS ArrColor}",
"    }",
"}]}",
"Transform {",
" translation 0 2 0",
" children [Shape { geometry Cone {bottomRadius 0.2 height 0.4}",
"    appearance Appearance {",
"	material Material {diffuseColor IS ArrColor}",
"    }}",
"]}]}}",
"PROTO axes [field SFColor MyColor 0.6 0.2 0.6]",
"{",
"Group{ children[",
"arrow {MyLabel \"y\" ArrColor IS MyColor}",
"Transform {translation 0.3 2 0 children [",
"Billboard{ children [Shape{geometry Text {string \"y\"}}]}]}",
"Transform{ rotation 1 0 0 1.57",
"           children [arrow {MyLabel \"z\" ArrColor IS MyColor}]}",
"Transform {translation 0.3 0 2 children [",
"Billboard{ children [Shape{geometry Text {string \"z\"}}]}]}",
"Transform{ rotation 0 0 1 -1.57",
"           children [arrow {MyLabel \"x\" ArrColor IS MyColor}]}",
"Transform {translation 2 0.3 0 children [",
"Billboard{ children [Shape{geometry Text {string \"x\"}}]}]}",
"]}}",
NULL
};

char *VRML_trailer[] = {
"#END OF FILE",
NULL
};

